### ISSUE TITLE
nerdmetric: A new metric for contributions to community resources

### ISSUE THREAD

**Issue by tsalo** [BrainhackMTL/informatics2018#1]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   nerdmetric    |
| Description    |   A new metric of researcher contributions to cognitive neuroscience community resources |
| URL(s)            |   https://brainhack.slack.com/messages/CB5AZLJTD |
| Contributors' Brainhack Slack handle |   @62442katieb, @akeshavan, @dbkeator, @emdupre, @gkiar, @jb, @tsalo |
| Image            |    ![image](https://user-images.githubusercontent.com/8228902/41246146-27b626cc-6d78-11e8-9626-eb2d15a58f24.png) |

**Comment by gkiar** [comment]
[Added](https://brainhackmtl.github.io/informatics2018/projects.html#project1) a while ago, but linking for posterity :)
