### ISSUE TITLE
brainsprite jupyter widget

### ISSUE THREAD

**Issue by lunebellec** [BrainhackMTL/informatics2018#18]
| Project Name |   *brainsprite jupyter widget*    |
|:--------------|:-------------|
| Description    |   *[brainsprite.js](https://simexp.github.io/brainsprite.js) is a leightweight javascript brain viewer. I am trying to create a python interface to brainsprite, and turn it into a jupyter notebook widget. We have started looking into the [jupyter widget "cookie cutter" template](https://github.com/jupyter-widgets/widget-cookiecutter), but it is quite complicated. I could very much use some help from anybody with experience with jupyter widgets, and/or the cookie cutter template for widgets.* |
| URL(s)            |   *https://simexp.github.io/brainsprite.js https://github.com/jupyter-widgets/widget-cookiecutter* |
| Contributors' Brainhack Slack handle |   pierre.bellec |
| Image            |    ![brainsprite](https://raw.githubusercontent.com/brainsprite/brainsprite.js/master/tests/example_overlay.jpg "brainsprite") |

**Comment by oganm** [comment]
Sorry for not being well versed in python but I have started writing an unsolicited R wrapper for this at https://github.com/oganm/brainspriteR. Aim is to have it work within rmarkdown files and shiny applications. Basic visualization is done. I just need to add support for overlay and clicks as inputs.

[Here](https://oganm.github.io/brainspriteR/test)'s the most basic example

**Comment by lunebellec** [comment]
this looks promising! Let's chat tomorrow.

**Comment by oganm** [comment]
I'm around. As a side note, can't seem to make the click input example work. Is that part implemented?

**Comment by oganm** [comment]
Some debugging let me to believe that the brain object isn't actually passed to the function as it appears to be undefined

Edit: I have pinpointed the problem [here](https://github.com/SIMEXP/brainsprite.js/blob/master/assets/brainsprite.js#L433). Replacing `e` with `brain` fixes the issue

**Comment by lunebellec** [comment]
MMMhhhh I guess this has to do with javascript scopes, which I don't really understand. I will have to dig into it, because I don't want the library to depend on the name used for the "brain" object.

**Comment by lunebellec** [comment]
other updates:
  * @akeshavan has implemented papaya as a jupyter lab extension. Code lives here https://github.com/akeshavan/nii_extension
  * nilearn has also incorporated papaya in notebooks. They have not used a jupyter widget, but instead an iframe. The code is super concise. Looks like a great solution, that should work with brainsprite. https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/html_stat_map.py

**Comment by lunebellec** [comment]
Actually, new nilearn papaya integration works as well as brainsprite. No point duplicating. Dropping this idea.

**Comment by lunebellec** [comment]
OK so after further investigation papaya's memory footprint is huge, and slow enough to spin that it still justifies working on the brainsprite architecture.

**Comment by lunebellec** [comment]
This project is continuing on https://github.com/brainsprite/brainsprite.py 
  Integration in notebooks is working.
