### ISSUE TITLE
qMRLab

### ISSUE THREAD

**Issue by mathieuboudreau** [BrainhackMTL/informatics2018#5]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   qMRLab    |
| Description    |   qMRLab is an open-source software for quantitative MR image analysis. The main goal is to provide the community with an intuitive tool for data fitting, plotting, simulation and protocol optimization for a myriad of different quantitative models. This project will involve integrating PSOM with qMRLab to pre-process the qMRI dependencies of more complicated qMRLab methods that depend on other quantitative MRI techniques (e.g. quantitative Magnetisation Transfer)|
| URL(s)            |   https://github.com/neuropoly/qMRLab |
| Contributors' Brainhack Slack handle |   @agahkarakuzu @mathieuboudreau |
| Image            |    ![alurnmz3_400x400](https://user-images.githubusercontent.com/1421029/43473253-0721a664-94c6-11e8-8c86-bf4498fedf30.jpg) |

**Comment by gkiar** [comment]
[Added](https://brainhackmtl.github.io/informatics2018/projects.html#project5)! Thanks :)
